from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
THEMES_DIR = ROOT / "themes"


THEMES = [
    {
        "theme_id": "theme-02",
        "slug": "my-school-day",
        "theme_label": "THEME 02",
        "title": "My school day",
        "folder_name": "2. Мой школьный день",
        "entries": [
            ("I wake up at seven o'clock on school days.", "В школьные дни я просыпаюсь в семь часов."),
            ("I make my bed before breakfast.", "Я заправляю кровать перед завтраком."),
            ("I wash my face and brush my teeth.", "Я умываюсь и чищу зубы."),
            ("I usually eat porridge, eggs, or sandwiches.", "Обычно я ем кашу, яйца или бутерброды."),
            ("I pack my books and notebooks into my school bag.", "Я складываю книги и тетради в школьный рюкзак."),
            ("I leave home at about eight o'clock.", "Я выхожу из дома примерно в восемь часов."),
            ("I go to school on foot or by bus.", "Я иду в школу пешком или еду на автобусе."),
            ("My lessons start at half past eight.", "Мои уроки начинаются в половине девятого."),
            ("The first lesson is often Maths or Russian.", "Первый урок часто бывает математика или русский язык."),
            ("I listen to my teachers carefully.", "Я внимательно слушаю учителей."),
            ("I like answering questions in class.", "Мне нравится отвечать на вопросы в классе."),
            ("During the break I talk to my classmates.", "На перемене я разговариваю с одноклассниками."),
            ("Sometimes I eat an apple or a bun at school.", "Иногда я ем яблоко или булочку в школе."),
            ("My favourite lesson is English.", "Мой любимый урок — английский."),
            ("I learn new words and short dialogues.", "Я учу новые слова и короткие диалоги."),
            ("After lessons I go home and have lunch.", "После уроков я иду домой и обедаю."),
            ("Then I do my homework in the afternoon.", "Потом я делаю домашнее задание днём."),
            ("If I have time, I read or draw.", "Если у меня есть время, я читаю или рисую."),
            ("In the evening I prepare my things for the next day.", "Вечером я готовлю вещи на следующий день."),
            ("I go to bed early because I want to feel fresh in the morning.", "Я ложусь спать рано, потому что хочу чувствовать себя бодро утром."),
        ],
    },
    {
        "theme_id": "theme-03",
        "slug": "my-classroom-and-classmates",
        "theme_label": "THEME 03",
        "title": "My classroom and classmates",
        "folder_name": "3. Класс и одноклассники",
        "entries": [
            ("My classroom is bright and comfortable.", "Мой класс светлый и удобный."),
            ("There are many desks and chairs in the room.", "В комнате много парт и стульев."),
            ("The teacher's desk is in front of the class.", "Учительский стол стоит перед классом."),
            ("We have a big board on the wall.", "У нас на стене большая доска."),
            ("Sometimes we use a projector during lessons.", "Иногда мы используем проектор на уроках."),
            ("There are maps, pictures, and posters in our classroom.", "В нашем классе есть карты, картинки и плакаты."),
            ("I usually sit near the window.", "Обычно я сижу у окна."),
            ("My best friend sits not far from me.", "Мой лучший друг сидит недалеко от меня."),
            ("My classmates are friendly and funny.", "Мои одноклассники дружелюбные и весёлые."),
            ("Some children like sports very much.", "Некоторые дети очень любят спорт."),
            ("Others enjoy reading books or drawing.", "Другие любят читать книги или рисовать."),
            ("We often work in pairs or in groups.", "Мы часто работаем в парах или в группах."),
            ("I like helping my classmates with difficult tasks.", "Мне нравится помогать одноклассникам с трудными заданиями."),
            ("My classmates also help me when I need it.", "Мои одноклассники тоже помогают мне, когда это нужно."),
            ("We celebrate birthdays together at school.", "Мы вместе празднуем дни рождения в школе."),
            ("Before holidays we decorate the classroom.", "Перед праздниками мы украшаем класс."),
            ("Our teacher teaches us to be kind and polite.", "Наша учительница учит нас быть добрыми и вежливыми."),
            ("I feel calm and happy in my classroom.", "Я чувствую себя спокойно и счастливо в своём классе."),
            ("It is nice to study with good classmates.", "Приятно учиться с хорошими одноклассниками."),
            ("I think our classroom is a special place for learning and friendship.", "Я думаю, что наш класс — особое место для учёбы и дружбы."),
        ],
    },
    {
        "theme_id": "theme-04",
        "slug": "my-best-friend",
        "theme_label": "THEME 04",
        "title": "My best friend",
        "folder_name": "4. Мой лучший друг",
        "entries": [
            ("My best friend is kind and cheerful.", "Мой лучший друг добрый и весёлый."),
            ("We study at the same school.", "Мы учимся в одной школе."),
            ("We first met in primary school.", "Мы впервые познакомились в начальной школе."),
            ("My friend has a warm smile and bright eyes.", "У моего друга тёплая улыбка и яркие глаза."),
            ("We like spending time together after lessons.", "Нам нравится проводить время вместе после уроков."),
            ("Sometimes we walk in the park.", "Иногда мы гуляем в парке."),
            ("Sometimes we do our homework together.", "Иногда мы вместе делаем домашнее задание."),
            ("My friend is good at Maths.", "Мой друг хорошо умеет решать математику."),
            ("I am good at English and reading.", "Я хорошо знаю английский и люблю читать."),
            ("We help each other with school work.", "Мы помогаем друг другу с учёбой."),
            ("My friend likes football and computer games.", "Мой друг любит футбол и компьютерные игры."),
            ("I like drawing and listening to music.", "Я люблю рисовать и слушать музыку."),
            ("We both enjoy funny stories.", "Нам обоим нравятся смешные истории."),
            ("When I feel sad, my friend can cheer me up.", "Когда мне грустно, мой друг умеет поднять мне настроение."),
            ("A good friend listens carefully and tells the truth.", "Хороший друг внимательно слушает и говорит правду."),
            ("We never laugh at each other's mistakes.", "Мы никогда не смеёмся над ошибками друг друга."),
            ("We say sorry if we do something wrong.", "Мы говорим «прости», если делаем что-то не так."),
            ("I can trust my best friend.", "Я могу доверять своему лучшему другу."),
            ("Friendship makes school life brighter.", "Дружба делает школьную жизнь ярче."),
            ("I am happy that I have such a wonderful best friend.", "Я счастлива, что у меня есть такой замечательный лучший друг."),
        ],
    },
    {
        "theme_id": "theme-05",
        "slug": "my-hobbies-and-free-time",
        "theme_label": "THEME 05",
        "title": "My hobbies and free time",
        "folder_name": "5. Хобби и свободное время",
        "entries": [
            ("I have several hobbies.", "У меня есть несколько увлечений."),
            ("My hobbies help me relax after school.", "Мои увлечения помогают мне отдыхать после школы."),
            ("I like drawing with pencils and paints.", "Я люблю рисовать карандашами и красками."),
            ("I often draw animals, flowers, and houses.", "Я часто рисую животных, цветы и дома."),
            ("I also enjoy reading adventure stories.", "Мне также нравится читать приключенческие истории."),
            ("Books can take me to interesting places.", "Книги могут перенести меня в интересные места."),
            ("Sometimes I listen to music in my room.", "Иногда я слушаю музыку у себя в комнате."),
            ("Music makes my mood better.", "Музыка улучшает моё настроение."),
            ("I like dancing when I hear my favourite songs.", "Я люблю танцевать, когда слышу любимые песни."),
            ("At weekends I sometimes ride a bike.", "По выходным я иногда катаюсь на велосипеде."),
            ("I enjoy walking outside in good weather.", "Мне нравится гулять на улице в хорошую погоду."),
            ("I play board games with my family.", "Я играю в настольные игры со своей семьёй."),
            ("Sometimes I watch educational videos.", "Иногда я смотрю познавательные видео."),
            ("I like learning new facts about animals and space.", "Мне нравится узнавать новые факты о животных и космосе."),
            ("I do not like being bored.", "Мне не нравится скучать."),
            ("I try to use my free time in a useful way.", "Я стараюсь использовать свободное время с пользой."),
            ("A hobby can teach patience and creativity.", "Хобби может научить терпению и творчеству."),
            ("It is good to have both active and quiet hobbies.", "Хорошо иметь и активные, и спокойные увлечения."),
            ("My hobbies make me feel happy and confident.", "Мои увлечения делают меня счастливой и уверенной."),
            ("I hope to find even more interesting hobbies in the future.", "Надеюсь, что в будущем найду ещё больше интересных увлечений."),
        ],
    },
    {
        "theme_id": "theme-06",
        "slug": "my-home-and-my-room",
        "theme_label": "THEME 06",
        "title": "My home and my room",
        "folder_name": "6. Дом и моя комната",
        "entries": [
            ("I live in a cosy home with my family.", "Я живу в уютном доме со своей семьёй."),
            ("Our home is warm and clean.", "Наш дом тёплый и чистый."),
            ("There is a kitchen, a bathroom, and several rooms.", "Там есть кухня, ванная и несколько комнат."),
            ("My favourite place at home is my room.", "Моё любимое место дома — моя комната."),
            ("My room is not very big, but it is comfortable.", "Моя комната не очень большая, но удобная."),
            ("I have a bed, a desk, and a chair there.", "У меня там есть кровать, стол и стул."),
            ("There is a bookshelf near the wall.", "Возле стены стоит книжная полка."),
            ("I keep my school books and toys on the shelves.", "Я храню школьные книги и игрушки на полках."),
            ("My desk is near the window.", "Мой стол стоит возле окна."),
            ("I do my homework at my desk every day.", "Я каждый день делаю домашнее задание за своим столом."),
            ("I have some posters and pictures in my room.", "У меня в комнате есть несколько плакатов и картинок."),
            ("My favourite colours make the room look cheerful.", "Мои любимые цвета делают комнату веселее."),
            ("I like to keep my room tidy.", "Мне нравится поддерживать порядок в комнате."),
            ("I put my clothes in the wardrobe.", "Я кладу одежду в шкаф."),
            ("I make my bed every morning.", "Я заправляю кровать каждое утро."),
            ("Sometimes I open the window to get fresh air.", "Иногда я открываю окно, чтобы впустить свежий воздух."),
            ("In the evening I read or draw in my room.", "Вечером я читаю или рисую у себя в комнате."),
            ("My room is a good place for rest and study.", "Моя комната — хорошее место для отдыха и учёбы."),
            ("I feel safe and peaceful at home.", "Дома я чувствую себя в безопасности и спокойно."),
            ("Home is the place where I can be myself.", "Дом — это место, где я могу быть собой."),
        ],
    },
    {
        "theme_id": "theme-07",
        "slug": "pets-and-animals",
        "theme_label": "THEME 07",
        "title": "Pets and animals",
        "folder_name": "7. Домашние животные и звери",
        "entries": [
            ("I love animals very much.", "Я очень люблю животных."),
            ("Some people have cats, dogs, parrots, or hamsters.", "У некоторых людей есть кошки, собаки, попугаи или хомяки."),
            ("A pet can be a real friend.", "Домашнее животное может быть настоящим другом."),
            ("Pets need food, water, and care every day.", "Домашним животным каждый день нужны еда, вода и забота."),
            ("A dog likes walking and playing outside.", "Собака любит гулять и играть на улице."),
            ("A cat likes sleeping in warm places.", "Кошка любит спать в тёплых местах."),
            ("Birds are small, bright, and lively.", "Птицы маленькие, яркие и живые."),
            ("Fish are quiet and beautiful to watch.", "За рыбками тихо и красиво наблюдать."),
            ("I think animals can feel love and fear.", "Я думаю, что животные могут чувствовать любовь и страх."),
            ("We must be kind to all living creatures.", "Мы должны быть добры ко всем живым существам."),
            ("Wild animals live in forests, fields, and mountains.", "Дикие животные живут в лесах, полях и горах."),
            ("Bears are strong and foxes are clever.", "Медведи сильные, а лисы хитрые."),
            ("Rabbits are soft and very cute.", "Кролики мягкие и очень милые."),
            ("Horses are beautiful and fast.", "Лошади красивые и быстрые."),
            ("I like visiting the zoo, but I like nature even more.", "Мне нравится ходить в зоопарк, но природу я люблю ещё больше."),
            ("Animals need clean water and safe homes.", "Животным нужны чистая вода и безопасные места для жизни."),
            ("People should not hurt animals.", "Люди не должны обижать животных."),
            ("Sometimes animals help people.", "Иногда животные помогают людям."),
            ("Pets can teach children responsibility.", "Домашние животные могут научить детей ответственности."),
            ("The world is better when people protect animals.", "Мир становится лучше, когда люди защищают животных."),
        ],
    },
    {
        "theme_id": "theme-08",
        "slug": "my-town-and-places",
        "theme_label": "THEME 08",
        "title": "My town and places around me",
        "folder_name": "8. Мой город и места вокруг",
        "entries": [
            ("I live in a nice town.", "Я живу в хорошем городе."),
            ("My town has streets, parks, and shops.", "В моём городе есть улицы, парки и магазины."),
            ("There are schools and playgrounds near my home.", "Рядом с моим домом есть школы и детские площадки."),
            ("I often go to the supermarket with my family.", "Я часто хожу в супермаркет с семьёй."),
            ("There is also a pharmacy and a post office nearby.", "Рядом также есть аптека и почта."),
            ("My favourite place in town is the park.", "Моё любимое место в городе — парк."),
            ("In the park I can walk, play, and ride a bike.", "В парке я могу гулять, играть и кататься на велосипеде."),
            ("Sometimes I feed birds there.", "Иногда я там кормлю птиц."),
            ("The library is another useful place.", "Библиотека — ещё одно полезное место."),
            ("People can borrow books and read quietly there.", "Люди могут брать там книги и тихо читать."),
            ("I also like the cinema in our town.", "Мне также нравится кинотеатр в нашем городе."),
            ("It is fun to watch films with friends or parents.", "Весело смотреть фильмы с друзьями или родителями."),
            ("There are buses and cars on the roads every day.", "На дорогах каждый день ездят автобусы и машины."),
            ("We must be careful when we cross the street.", "Мы должны быть осторожны, когда переходим улицу."),
            ("A clean town is pleasant for everybody.", "Чистый город приятен для всех."),
            ("People should not throw rubbish on the ground.", "Люди не должны бросать мусор на землю."),
            ("Trees and flowers make the town more beautiful.", "Деревья и цветы делают город красивее."),
            ("I know the way to school and to my favourite places.", "Я знаю дорогу до школы и до своих любимых мест."),
            ("It is good to feel at home in your town.", "Хорошо чувствовать себя как дома в своём городе."),
            ("I like learning more about the place where I live.", "Мне нравится узнавать больше о месте, где я живу."),
        ],
    },
    {
        "theme_id": "theme-09",
        "slug": "seasons-and-weather",
        "theme_label": "THEME 09",
        "title": "Seasons and weather",
        "folder_name": "9. Времена года и погода",
        "entries": [
            ("There are four seasons in a year.", "В году четыре времени года."),
            ("They are spring, summer, autumn, and winter.", "Это весна, лето, осень и зима."),
            ("Each season is beautiful in its own way.", "Каждое время года красиво по-своему."),
            ("In spring the days become warmer and longer.", "Весной дни становятся теплее и длиннее."),
            ("Flowers bloom and trees turn green.", "Цветы распускаются, а деревья зеленеют."),
            ("In summer the weather is often hot and sunny.", "Летом погода часто жаркая и солнечная."),
            ("Children like swimming, playing, and travelling in summer.", "Летом детям нравится плавать, играть и путешествовать."),
            ("Autumn is cool, windy, and colourful.", "Осень прохладная, ветреная и разноцветная."),
            ("Leaves turn yellow, orange, and red.", "Листья становятся жёлтыми, оранжевыми и красными."),
            ("Sometimes it rains a lot in autumn.", "Иногда осенью много дождей."),
            ("Winter is cold and snowy.", "Зима холодная и снежная."),
            ("I like making a snowman and throwing snowballs.", "Мне нравится лепить снеговика и играть в снежки."),
            ("The sky can be clear, cloudy, or grey.", "Небо может быть ясным, облачным или серым."),
            ("The weather can change quickly.", "Погода может быстро меняться."),
            ("That is why people check the weather forecast.", "Поэтому люди смотрят прогноз погоды."),
            ("On rainy days I wear a raincoat or take an umbrella.", "В дождливые дни я надеваю плащ или беру зонт."),
            ("On cold days I wear a hat, scarf, and gloves.", "В холодные дни я надеваю шапку, шарф и перчатки."),
            ("I enjoy sunny weather the most.", "Больше всего мне нравится солнечная погода."),
            ("Still, every season has fun activities.", "Но у каждого времени года есть весёлые занятия."),
            ("Nature looks different in every season, and that is wonderful.", "Природа выглядит по-разному в каждое время года, и это замечательно."),
        ],
    },
    {
        "theme_id": "theme-10",
        "slug": "food-and-healthy-meals",
        "theme_label": "THEME 10",
        "title": "Food and healthy meals",
        "folder_name": "10. Еда и полезные блюда",
        "entries": [
            ("Food gives us energy for school and play.", "Еда даёт нам энергию для школы и игр."),
            ("I like tasty meals, but I also try to eat healthy food.", "Я люблю вкусную еду, но стараюсь есть и полезную пищу."),
            ("For breakfast I often eat porridge, eggs, or yoghurt.", "На завтрак я часто ем кашу, яйца или йогурт."),
            ("Fruit is a good snack during the day.", "Фрукты — хороший перекус в течение дня."),
            ("Apples, bananas, and oranges are healthy and sweet.", "Яблоки, бананы и апельсины полезные и сладкие."),
            ("Vegetables are important too.", "Овощи тоже важны."),
            ("I eat cucumbers, tomatoes, carrots, and potatoes.", "Я ем огурцы, помидоры, морковь и картофель."),
            ("Soup is warm and filling.", "Суп тёплый и сытный."),
            ("Many children like pasta, rice, or mashed potatoes.", "Многие дети любят макароны, рис или пюре."),
            ("Chicken and fish can be part of a healthy lunch.", "Курица и рыба могут быть частью полезного обеда."),
            ("I drink water every day.", "Я каждый день пью воду."),
            ("Too many sweets are not good for our teeth.", "Слишком много сладкого вредно для зубов."),
            ("Fast food may be tasty, but it should not be eaten too often.", "Фастфуд может быть вкусным, но его не стоит есть слишком часто."),
            ("My family sometimes cooks dinner together.", "Моя семья иногда готовит ужин вместе."),
            ("I can help wash vegetables or set the table.", "Я могу помочь помыть овощи или накрыть на стол."),
            ("It is polite to say thank you for the meal.", "Вежливо говорить спасибо за еду."),
            ("I like learning simple recipes.", "Мне нравится узнавать простые рецепты."),
            ("Healthy food helps us grow strong.", "Полезная еда помогает нам расти сильными."),
            ("A balanced diet is important for children.", "Сбалансированное питание важно для детей."),
            ("Good food and good habits can keep us active and cheerful.", "Хорошая еда и хорошие привычки помогают нам быть активными и весёлыми."),
        ],
    },
    {
        "theme_id": "theme-11",
        "slug": "shopping-and-clothes",
        "theme_label": "THEME 11",
        "title": "Shopping and clothes",
        "folder_name": "11. Покупки и одежда",
        "entries": [
            ("People go shopping to buy food, clothes, and other things.", "Люди ходят за покупками, чтобы купить еду, одежду и другие вещи."),
            ("I sometimes go to the shop with my parents.", "Иногда я хожу в магазин с родителями."),
            ("A supermarket is big and has many products.", "Супермаркет большой и в нём много товаров."),
            ("A clothes shop has dresses, trousers, shirts, and shoes.", "В магазине одежды есть платья, брюки, рубашки и обувь."),
            ("I like wearing comfortable clothes.", "Мне нравится носить удобную одежду."),
            ("At school I wear neat clothes every day.", "В школу я каждый день надеваю аккуратную одежду."),
            ("In winter I wear a warm coat and boots.", "Зимой я ношу тёплое пальто и сапоги."),
            ("In summer I wear a T-shirt, shorts, or a light dress.", "Летом я ношу футболку, шорты или лёгкое платье."),
            ("My favourite colours for clothes are blue and green.", "Мои любимые цвета в одежде — синий и зелёный."),
            ("Before buying clothes people often try them on.", "Перед покупкой одежды люди часто её примеряют."),
            ("The size must be right.", "Размер должен подходить."),
            ("The clothes should not be too tight or too loose.", "Одежда не должна быть слишком тесной или слишком свободной."),
            ("Comfort is important for active children.", "Для активных детей важен комфорт."),
            ("In a shop we must be polite to the shop assistant.", "В магазине мы должны быть вежливы с продавцом."),
            ("We can ask how much something costs.", "Мы можем спросить, сколько что-то стоит."),
            ("Sometimes there are discounts and sales.", "Иногда бывают скидки и распродажи."),
            ("It is better to buy useful things, not only pretty things.", "Лучше покупать полезные вещи, а не только красивые."),
            ("I try to keep my clothes clean and tidy.", "Я стараюсь держать одежду чистой и аккуратной."),
            ("I put my clothes away after wearing them.", "После носки я убираю одежду на место."),
            ("Shopping is easier when we know what we need.", "Покупки становятся проще, когда мы знаем, что нам нужно."),
        ],
    },
    {
        "theme_id": "theme-12",
        "slug": "birthdays-and-holidays",
        "theme_label": "THEME 12",
        "title": "Birthdays and holidays",
        "folder_name": "12. Дни рождения и праздники",
        "entries": [
            ("Holidays are special days for rest and joy.", "Праздники — это особые дни для отдыха и радости."),
            ("My birthday is one of my favourite days of the year.", "Мой день рождения — один из моих любимых дней в году."),
            ("I like celebrating it with my family and friends.", "Мне нравится праздновать его с семьёй и друзьями."),
            ("We usually decorate the room with balloons.", "Обычно мы украшаем комнату шарами."),
            ("There is often a birthday cake on the table.", "На столе часто бывает праздничный торт."),
            ("I blow out the candles and make a wish.", "Я задуваю свечи и загадываю желание."),
            ("My guests say kind words to me.", "Гости говорят мне добрые слова."),
            ("I am happy to get cards and presents.", "Я рада получать открытки и подарки."),
            ("I also like giving small presents to other people.", "Мне также нравится дарить маленькие подарки другим людям."),
            ("New Year is another wonderful holiday.", "Новый год — ещё один замечательный праздник."),
            ("People decorate a tree and prepare tasty food.", "Люди украшают ёлку и готовят вкусную еду."),
            ("Many children wait for winter holidays with excitement.", "Многие дети с волнением ждут зимних каникул."),
            ("Some holidays are family holidays.", "Некоторые праздники — семейные."),
            ("Others are national holidays for the whole country.", "Другие — государственные праздники для всей страны."),
            ("On holidays people often visit relatives.", "В праздники люди часто навещают родственников."),
            ("We can play games, sing songs, and take photos.", "Мы можем играть, петь песни и фотографироваться."),
            ("A holiday is not only about food and gifts.", "Праздник — это не только еда и подарки."),
            ("It is also about love, time together, and warm memories.", "Это ещё и любовь, время вместе и тёплые воспоминания."),
            ("I enjoy happy days with the people I love.", "Мне нравятся счастливые дни с людьми, которых я люблю."),
            ("Good holidays stay in our hearts for a long time.", "Хорошие праздники надолго остаются в нашем сердце."),
        ],
    },
    {
        "theme_id": "theme-13",
        "slug": "weekend-and-family-time",
        "theme_label": "THEME 13",
        "title": "Weekend and family time",
        "folder_name": "13. Выходные и время с семьёй",
        "entries": [
            ("I always wait for the weekend.", "Я всегда жду выходных."),
            ("At the weekend I do not go to school.", "В выходные я не хожу в школу."),
            ("I can wake up a little later.", "Я могу проснуться немного позже."),
            ("My family often has breakfast together.", "Моя семья часто завтракает вместе."),
            ("We talk, laugh, and make plans for the day.", "Мы разговариваем, смеёмся и строим планы на день."),
            ("Sometimes we go for a walk in the park.", "Иногда мы идём гулять в парк."),
            ("Sometimes we visit grandparents or other relatives.", "Иногда мы навещаем бабушку, дедушку или других родственников."),
            ("I like family picnics in warm weather.", "Мне нравятся семейные пикники в тёплую погоду."),
            ("At home we can watch a film together.", "Дома мы можем вместе посмотреть фильм."),
            ("We also play board games and card games.", "Мы также играем в настольные и карточные игры."),
            ("Sometimes I help my parents at home.", "Иногда я помогаю родителям дома."),
            ("I can tidy my room or help in the kitchen.", "Я могу убрать комнату или помочь на кухне."),
            ("On Sunday I usually do some homework.", "В воскресенье я обычно делаю часть домашней работы."),
            ("It is better to finish homework before Monday.", "Лучше закончить домашнюю работу до понедельника."),
            ("I also try to rest and enjoy my hobbies.", "Я также стараюсь отдыхать и заниматься своими хобби."),
            ("My family likes talking about school and life.", "Моя семья любит разговаривать о школе и жизни."),
            ("Family time makes me feel loved and safe.", "Время с семьёй даёт мне чувство любви и безопасности."),
            ("Weekends help me get ready for a new week.", "Выходные помогают мне подготовиться к новой неделе."),
            ("I think simple family moments are very important.", "Я думаю, что простые семейные моменты очень важны."),
            ("A good weekend gives me energy and a good mood.", "Хорошие выходные дают мне энергию и хорошее настроение."),
        ],
    },
    {
        "theme_id": "theme-14",
        "slug": "sports-and-games",
        "theme_label": "THEME 14",
        "title": "Sports and games",
        "folder_name": "14. Спорт и игры",
        "entries": [
            ("Sport is good for children and adults.", "Спорт полезен для детей и взрослых."),
            ("It helps us stay strong and healthy.", "Он помогает нам быть сильными и здоровыми."),
            ("I like active games and movement.", "Мне нравятся активные игры и движение."),
            ("At school we have PE lessons.", "В школе у нас есть уроки физкультуры."),
            ("During PE we run, jump, and play team games.", "На физкультуре мы бегаем, прыгаем и играем в командные игры."),
            ("Some children like football or basketball.", "Некоторым детям нравится футбол или баскетбол."),
            ("Others prefer swimming, dancing, or gymnastics.", "Другие предпочитают плавание, танцы или гимнастику."),
            ("I enjoy outdoor games with my friends.", "Мне нравятся игры на улице с друзьями."),
            ("Tag and hide-and-seek are simple but fun.", "Салки и прятки простые, но весёлые."),
            ("Sport teaches us to follow rules.", "Спорт учит нас соблюдать правила."),
            ("It also teaches teamwork and patience.", "Он также учит работать в команде и быть терпеливыми."),
            ("Winning is nice, but trying your best is more important.", "Побеждать приятно, но важнее стараться изо всех сил."),
            ("It is okay to lose sometimes.", "Иногда проигрывать — это нормально."),
            ("We can learn from every game.", "Мы можем учиться в каждой игре."),
            ("I like cheering for my friends.", "Мне нравится болеть за друзей."),
            ("Warm-up exercises are important before sport.", "Разминка важна перед спортом."),
            ("Water is important after exercise.", "После упражнений важно пить воду."),
            ("Too much screen time is not as good as active play.", "Слишком много времени за экраном не так полезно, как активные игры."),
            ("Sport can make us brave and disciplined.", "Спорт может сделать нас смелыми и дисциплинированными."),
            ("I want to stay active and enjoy movement every week.", "Я хочу оставаться активной и радоваться движению каждую неделю."),
        ],
    },
    {
        "theme_id": "theme-15",
        "slug": "books-and-reading",
        "theme_label": "THEME 15",
        "title": "Books and reading",
        "folder_name": "15. Книги и чтение",
        "entries": [
            ("Books are our quiet friends.", "Книги — наши тихие друзья."),
            ("Reading helps us learn new things.", "Чтение помогает нам узнавать новое."),
            ("I like reading stories in the evening.", "Мне нравится читать истории вечером."),
            ("Adventure books are exciting and fun.", "Приключенческие книги увлекательные и интересные."),
            ("Fairy tales can be magical and kind.", "Сказки могут быть волшебными и добрыми."),
            ("Some books make us laugh.", "Некоторые книги заставляют нас смеяться."),
            ("Other books make us think deeply.", "Другие книги заставляют нас задуматься."),
            ("I often read at home in a cosy place.", "Я часто читаю дома в уютном месте."),
            ("Sometimes I borrow books from the library.", "Иногда я беру книги в библиотеке."),
            ("A library is a wonderful place for readers.", "Библиотека — замечательное место для читателей."),
            ("Reading improves our imagination.", "Чтение развивает наше воображение."),
            ("It also helps us remember words and ideas.", "Оно также помогает запоминать слова и идеи."),
            ("I like books with interesting characters.", "Мне нравятся книги с интересными героями."),
            ("A good story can take us to another world.", "Хорошая история может перенести нас в другой мир."),
            ("Sometimes I read alone and sometimes with my family.", "Иногда я читаю одна, а иногда с семьёй."),
            ("Parents can read aloud to children.", "Родители могут читать детям вслух."),
            ("That makes reading warm and special.", "Это делает чтение тёплым и особенным."),
            ("I think reading is better than being bored.", "Я думаю, что читать лучше, чем скучать."),
            ("Every book can teach us something useful.", "Каждая книга может научить нас чему-то полезному."),
            ("I hope I will always have time for books.", "Надеюсь, у меня всегда будет время для книг."),
        ],
    },
    {
        "theme_id": "theme-16",
        "slug": "travel-and-transport",
        "theme_label": "THEME 16",
        "title": "Travel and transport",
        "folder_name": "16. Путешествия и транспорт",
        "entries": [
            ("Travelling can be exciting and educational.", "Путешествия могут быть увлекательными и познавательными."),
            ("People travel to see new places.", "Люди путешествуют, чтобы увидеть новые места."),
            ("They also travel to meet relatives or have отдых.", "Они также путешествуют, чтобы навестить родных или отдохнуть."),
            ("There are many kinds of transport.", "Существует много видов транспорта."),
            ("People can travel by car, bus, train, or plane.", "Люди могут путешествовать на машине, автобусе, поезде или самолёте."),
            ("A train journey can be long but comfortable.", "Путешествие на поезде может быть долгим, но удобным."),
            ("A plane is fast for long distances.", "Самолёт быстро преодолевает большие расстояния."),
            ("A bus is useful in towns and cities.", "Автобус полезен в городах."),
            ("A bicycle is good for short trips and exercise.", "Велосипед хорош для коротких поездок и физической активности."),
            ("Before a trip people pack their bags.", "Перед поездкой люди собирают вещи."),
            ("They take clothes, documents, and other important things.", "Они берут одежду, документы и другие важные вещи."),
            ("It is useful to have a plan for the trip.", "Полезно иметь план поездки."),
            ("We should be careful at stations and airports.", "Нужно быть внимательными на вокзалах и в аэропортах."),
            ("It is important to follow safety rules.", "Важно соблюдать правила безопасности."),
            ("I like looking out of the window when I travel.", "Мне нравится смотреть в окно во время поездки."),
            ("I can see fields, houses, rivers, and roads.", "Я могу видеть поля, дома, реки и дороги."),
            ("Travelling teaches us about the world.", "Путешествия учат нас миру."),
            ("It can also teach patience and organisation.", "Они также могут научить терпению и организованности."),
            ("I would like to visit many beautiful places one day.", "Однажды я хотела бы посетить много красивых мест."),
            ("Every trip can become a happy memory.", "Каждая поездка может стать счастливым воспоминанием."),
        ],
    },
    {
        "theme_id": "theme-17",
        "slug": "nature-and-the-countryside",
        "theme_label": "THEME 17",
        "title": "Nature and the countryside",
        "folder_name": "17. Природа и деревня",
        "entries": [
            ("Nature is beautiful in every season.", "Природа прекрасна в любое время года."),
            ("I like forests, rivers, fields, and hills.", "Мне нравятся леса, реки, поля и холмы."),
            ("The countryside is quiet and peaceful.", "За городом тихо и спокойно."),
            ("There is fresh air and a lot of space there.", "Там свежий воздух и много простора."),
            ("People can hear birds singing in the morning.", "Утром можно слышать пение птиц."),
            ("Trees give shade on hot summer days.", "Деревья дают тень в жаркие летние дни."),
            ("Flowers make fields and gardens colourful.", "Цветы делают поля и сады яркими."),
            ("I like walking on forest paths.", "Мне нравится гулять по лесным тропинкам."),
            ("Sometimes I collect leaves or cones.", "Иногда я собираю листья или шишки."),
            ("Rivers and lakes are important for animals and people.", "Реки и озёра важны для животных и людей."),
            ("We must not throw rubbish into nature.", "Мы не должны бросать мусор в природу."),
            ("Animals need clean places to live.", "Животным нужны чистые места для жизни."),
            ("Plants also need care and protection.", "Растениям тоже нужны забота и защита."),
            ("I enjoy picnics in the countryside.", "Мне нравятся пикники за городом."),
            ("It is fun to sit on the grass and look at the sky.", "Весело сидеть на траве и смотреть на небо."),
            ("Clouds can look like animals or ships.", "Облака могут быть похожи на животных или корабли."),
            ("Nature helps people rest from noisy city life.", "Природа помогает людям отдыхать от шумной городской жизни."),
            ("I feel calm when I spend time outdoors.", "Я чувствую спокойствие, когда провожу время на улице."),
            ("The Earth is our home, so we must protect it.", "Земля — наш дом, поэтому мы должны её беречь."),
            ("A love of nature can make us kinder and more careful.", "Любовь к природе может сделать нас добрее и внимательнее."),
        ],
    },
    {
        "theme_id": "theme-18",
        "slug": "technology-and-gadgets",
        "theme_label": "THEME 18",
        "title": "Technology and gadgets",
        "folder_name": "18. Технологии и гаджеты",
        "entries": [
            ("Technology is part of our everyday life.", "Технологии — часть нашей повседневной жизни."),
            ("Many people use phones, tablets, and computers.", "Многие люди пользуются телефонами, планшетами и компьютерами."),
            ("A computer can help with school work.", "Компьютер может помочь с учёбой."),
            ("We can type texts and look for information.", "Мы можем печатать тексты и искать информацию."),
            ("A tablet is useful for reading and watching videos.", "Планшет полезен для чтения и просмотра видео."),
            ("A phone can help people call and send messages.", "Телефон помогает людям звонить и отправлять сообщения."),
            ("Technology can save time.", "Технологии могут экономить время."),
            ("It can also make learning more interesting.", "Они также могут делать учёбу интереснее."),
            ("But gadgets should be used wisely.", "Но гаджетами нужно пользоваться разумно."),
            ("Too much screen time is not healthy.", "Слишком много времени у экрана вредно."),
            ("Children should rest their eyes.", "Детям нужно давать глазам отдых."),
            ("It is important to move and play outside too.", "Важно также двигаться и играть на улице."),
            ("We should not share personal information online.", "Мы не должны делиться личной информацией в интернете."),
            ("The internet can be helpful, but we must be careful.", "Интернет может быть полезным, но нужно быть осторожными."),
            ("Parents and teachers can help children stay safe online.", "Родители и учителя могут помочь детям оставаться в безопасности в интернете."),
            ("I like using technology for learning languages.", "Мне нравится использовать технологии для изучения языков."),
            ("Some apps help with vocabulary and pronunciation.", "Некоторые приложения помогают со словами и произношением."),
            ("Technology is better when it helps people do good things.", "Технологии лучше всего, когда помогают людям делать полезные вещи."),
            ("It is good to have balance between gadgets and real life.", "Хорошо сохранять баланс между гаджетами и реальной жизнью."),
            ("Smart use of technology can make life easier and brighter.", "Умное использование технологий может сделать жизнь проще и ярче."),
        ],
    },
    {
        "theme_id": "theme-19",
        "slug": "helping-at-home",
        "theme_label": "THEME 19",
        "title": "Helping at home",
        "folder_name": "19. Помощь по дому",
        "entries": [
            ("Every family member can help at home.", "Каждый член семьи может помогать дома."),
            ("Children can do simple tasks every day.", "Дети могут выполнять простые дела каждый день."),
            ("I can make my bed in the morning.", "Я могу заправлять кровать утром."),
            ("I can put my toys and books back in place.", "Я могу убирать игрушки и книги на место."),
            ("It is important to keep my room tidy.", "Важно поддерживать порядок в комнате."),
            ("I can wipe the table after meals.", "Я могу вытирать стол после еды."),
            ("Sometimes I help wash vegetables in the kitchen.", "Иногда я помогаю мыть овощи на кухне."),
            ("I can also set the table before dinner.", "Я также могу накрыть на стол перед ужином."),
            ("Helping at home is part of responsibility.", "Помощь по дому — это часть ответственности."),
            ("Parents do many things for the family.", "Родители делают много дел для семьи."),
            ("Children should not leave all the work to adults.", "Дети не должны оставлять всю работу взрослым."),
            ("When everyone helps, the house becomes cleaner faster.", "Когда помогают все, дом становится чистым быстрее."),
            ("Helping can also be a way to show love.", "Помощь также может быть способом показать любовь."),
            ("Sometimes I water the flowers at home.", "Иногда я поливаю цветы дома."),
            ("Sometimes I help carry light shopping bags.", "Иногда я помогаю нести лёгкие сумки из магазина."),
            ("I always try to do my tasks carefully.", "Я всегда стараюсь выполнять свои дела аккуратно."),
            ("It feels good to be useful.", "Приятно быть полезной."),
            ("Small actions can make a big difference.", "Маленькие действия могут многое изменить."),
            ("Good habits at home are important for the future.", "Хорошие домашние привычки важны для будущего."),
            ("I want to be a helpful person in my family.", "Я хочу быть полезным человеком в своей семье."),
        ],
    },
    {
        "theme_id": "theme-20",
        "slug": "school-subjects-and-projects",
        "theme_label": "THEME 20",
        "title": "School subjects and projects",
        "folder_name": "20. Школьные предметы и проекты",
        "entries": [
            ("At school we study many interesting subjects.", "В школе мы изучаем много интересных предметов."),
            ("Russian and Maths are very important.", "Русский язык и математика очень важны."),
            ("English helps us speak to people from other countries.", "Английский помогает нам говорить с людьми из других стран."),
            ("History tells us about the past.", "История рассказывает нам о прошлом."),
            ("Geography teaches us about countries, rivers, and mountains.", "География учит нас странам, рекам и горам."),
            ("Biology helps us understand plants, animals, and the human body.", "Биология помогает понимать растения, животных и человеческое тело."),
            ("Art lets us be creative.", "ИЗО позволяет нам быть творческими."),
            ("Music teaches us to listen and feel rhythm.", "Музыка учит нас слушать и чувствовать ритм."),
            ("PE helps us stay fit and active.", "Физкультура помогает нам быть в форме и активными."),
            ("Some lessons are easy for me.", "Некоторые уроки для меня лёгкие."),
            ("Some lessons are more difficult, but I still try hard.", "Некоторые уроки труднее, но я всё равно стараюсь."),
            ("Projects are a fun part of school life.", "Проекты — интересная часть школьной жизни."),
            ("A project can be about nature, books, or famous people.", "Проект может быть о природе, книгах или известных людях."),
            ("We can make posters, slides, or drawings for a project.", "Для проекта мы можем делать плакаты, слайды или рисунки."),
            ("Sometimes we work on projects in groups.", "Иногда мы работаем над проектами в группах."),
            ("That teaches us to share ideas.", "Это учит нас делиться идеями."),
            ("A good project needs time and attention.", "Хороший проект требует времени и внимания."),
            ("I feel proud when I finish my work well.", "Я горжусь собой, когда хорошо заканчиваю работу."),
            ("Every school subject can be useful in life.", "Каждый школьный предмет может пригодиться в жизни."),
            ("Learning new things helps me grow every day.", "Изучение нового помогает мне расти каждый день."),
        ],
    },
    {
        "theme_id": "theme-21",
        "slug": "dreams-and-future-plans",
        "theme_label": "THEME 21",
        "title": "Dreams and future plans",
        "folder_name": "21. Мечты и планы на будущее",
        "entries": [
            ("Every child has dreams about the future.", "У каждого ребёнка есть мечты о будущем."),
            ("Dreams can be small or big.", "Мечты могут быть маленькими или большими."),
            ("Some children want to travel the world.", "Некоторые дети хотят путешествовать по миру."),
            ("Some want to become teachers, doctors, or artists.", "Некоторые хотят стать учителями, врачами или художниками."),
            ("I also think about my future.", "Я тоже думаю о своём будущем."),
            ("First of all, I want to study well.", "Прежде всего я хочу хорошо учиться."),
            ("Good knowledge can help me later.", "Хорошие знания помогут мне потом."),
            ("I want to become a kind and smart person.", "Я хочу стать добрым и умным человеком."),
            ("I hope to have interesting hobbies when I grow up.", "Надеюсь, что у меня будут интересные увлечения, когда я вырасту."),
            ("I want to keep learning new things.", "Я хочу продолжать узнавать новое."),
            ("It is important to work hard for your dreams.", "Важно усердно работать ради своих мечт."),
            ("Sometimes dreams change with time.", "Иногда мечты со временем меняются."),
            ("That is normal and not scary.", "Это нормально и не страшно."),
            ("New experiences can show us new goals.", "Новый опыт может показать нам новые цели."),
            ("I would like to speak English confidently in the future.", "Я хотела бы уверенно говорить по-английски в будущем."),
            ("I also want to help other people.", "Я также хочу помогать другим людям."),
            ("A happy future needs kindness and effort.", "Счастливое будущее требует доброты и усилий."),
            ("It is good to believe in yourself.", "Хорошо верить в себя."),
            ("Step by step we can move toward our goals.", "Шаг за шагом мы можем двигаться к своим целям."),
            ("My dreams give me hope, energy, and inspiration.", "Мои мечты дают мне надежду, энергию и вдохновение."),
        ],
    },
]


def write_theme(theme: dict) -> None:
    folder = THEMES_DIR / f"{theme['theme_id']}__{theme['slug']}"
    folder.mkdir(parents=True, exist_ok=True)
    payload = {
        "theme_id": theme["theme_id"],
        "slug": theme["slug"],
        "theme_label": theme["theme_label"],
        "title": theme["title"],
        "folder_name": theme["folder_name"],
        "video": {
            "width": 1280,
            "height": 720,
            "fps": 24,
            "background_color": "#F6F0E5",
        },
        "entries": [{"en": en, "ru": ru} for en, ru in theme["entries"]],
    }
    (folder / "theme.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    for theme in THEMES:
        write_theme(theme)
    print(f"Created {len(THEMES)} additional themes.")


if __name__ == "__main__":
    main()
